name: 打包todos部署到github pages 

on: push

permissions:
  contents: write

jobs:
  npm-build:
    name: npm build 工作流
    runs-on: ubuntu-latest
    steps:
    - name: 读取仓库
      uses: actions/checkout@v3

    - name: 安装依赖和项目打包
      run: |
        npm install
        npm run build


    - name: 项目部署
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: dist